### PR TITLE
Create tokens for non-tokenized whitespace when importing from relANNIS

### PR DESCRIPTION
**Pull request by thomaskrause**
Since the text of the primary data sources is not stored as a label (because this would be huge for some texts), we need another way to reconstruct the original primary text for documents imported from relANNIS. By adding the white space segments as tokens (but with the special node type "white-space-token") and connected them with ordering edges this becomes possible.

### CODE REVIEW

**Comment by amir-zeldes** [comment]
@thomaskrause I saw this, and while I have no idea about the implementation and performance details, this sounded really expensive to me, since it effectively doubles the token count. Have you considered using a 'following whitespace' attribute, so that trailing whitespace becomes something like 'one more column' in the data model rather than a token? This is what UD does with `SpaceAfter`:

https://github.com/UniversalDependencies/UD_English-GUM/blob/master/en_gum-ud-dev.conllu#L15

Just a thought!

**Comment by thomaskrause** [comment]
Thanks for the hint to the UD implementation of this. I did some smaller benchmarks but still need to test it on a full benchmark set to know for sure. The additional edge component is not that problematic because it's just ignored for search but the node annotation count is going up indeed. For the relANNIS implementation I made sure these token are neither counted for `tok` or `node` queries to ensure backward-compatibility. Adding an implementation like the UD solution would also need some additional node annotations for the new category "SpaceAfter", but less than adding a full node: A token node has at least three annotations, the node type, name and the token value, just having the "SpaceAfter" category would only add one node annotation. I will report back when I have the full benchmark done, probably I will also compare the disk-based node annotation storage with the in memory one to see if the overhead in space can be avoided by using the disk.

**Comment by thomaskrause** [comment]
P.S. Having three additional node annotations instead of only one is of course also a significant overhead. Especially since the node name needs to be unique and therefore will occupy relatively large space in the dictionary. I will try to implement the alternative approach and see how it compares in flexibility.

**Comment by amir-zeldes** [comment]
Great, glad if it helps. You'll also need a possible initial pseudo token if the field always represents *trailing* whitespace, but I think it could be a solid and fairly minimalistic approach (since you have to have this info somewhere, and adding zero nodes seems to be the most economic). Another way would be to store just a second data structure on the side with pointers to those tokens that have trailing white space. That saves you the empty field for tokens that don't, but gives the overhead of joining the information to the relevant tokens, so it seems less optimal to me (but not knowing about the implementation I don't really know).

Happy to bounce around more ideas if you like!

**Pull request merged**
